switch:
  - platform: phicomm_dc1_switch
    name: dc1_1
    hidden: true
    ip: 192.168.2.103
    ports: {'1':'dc1_1_s1','2':'dc1_1_s2','3':'dc1_1_s3'}
  - platform: phicomm_dc1_switch
    name: dc1_2
    hidden: true
    ip: 192.168.2.162
    ports: {'1':'dc1_2_s1','2':'dc1_2_s2','3':'dc1_2_s3'}
  - platform: phicomm_dc1_switch
    name: dc1_3
    hidden: true
    ip: 192.168.2.123
    ports: {'1':'dc1_3_s1','2':'dc1_3_s2','3':'dc1_3_s3'}

sensor:
  - platform: template
    sensors:
      dc1_1_v:
        friendly_name: 当前电压
        value_template: "{{ states.switch.dc1_1.attributes.v }}"
        unit_of_measurement: V
      dc1_1_p:
        friendly_name: 当前功率
        value_template: "{{ states.switch.dc1_1.attributes.p }}"
        unit_of_measurement: W

  - platform: template
    sensors:
      dc1_2_v:
        friendly_name: 当前电压
        value_template: "{{ states.switch.dc1_2.attributes.v }}"
        unit_of_measurement: V
      dc1_2_p:
        friendly_name: 当前功率
        value_template: "{{ states.switch.dc1_2.attributes.p }}"
        unit_of_measurement: W

  - platform: template
    sensors:
      dc1_3_v:
        friendly_name: 当前电压
        value_template: "{{ states.switch.dc1_3.attributes.v }}"
        unit_of_measurement: V
      dc1_3_p:
        friendly_name: 当前功率
        value_template: "{{ states.switch.dc1_3.attributes.p }}"
        unit_of_measurement: W
      # dc1_3_totale:
      #   friendly_name: 累计用电
      #   value_template: "{{ states.switch.dc1_3.attributes.totalelect }}"
      #   unit_of_measurement: 度

group:
  dc1_1:
    name: 排插1
    view: false
    entities:
      - sensor.dc1_1_v
      - sensor.dc1_1_p
    # - sensor.dc1_1_totale
      - switch.dc1_1
      - switch.dc1_1_s1
      - switch.dc1_1_s2
      - switch.dc1_1_s3
  dc1_2:
    name: 排插2
    view: false
    entities:
      - sensor.dc1_2_v
      - sensor.dc1_2_p
    # - sensor.dc1_2_totale
      - switch.dc1_2
      - switch.dc1_2_s1
      - switch.dc1_2_s2
      - switch.dc1_2_s3
  dc1_3:
    name: 排插3
    view: false
    entities:
      - sensor.dc1_3_v
      - sensor.dc1_3_p
    # - sensor.dc1_3_totale
      - switch.dc1_3
      - switch.dc1_3_s1
      - switch.dc1_3_s2
      - switch.dc1_3_s3

homeassistant:        
  customize:
    switch.dc1_1:
      friendly_name: 电源开关
    switch.dc1_1_s1:
      friendly_name: 自定义
    switch.dc1_1_s2:
      friendly_name: 自定义
    switch.dc1_1_s3:
      friendly_name: 自定义

    switch.dc1_2:
      friendly_name: 电源开关
    switch.dc1_2_s1:
      friendly_name: 自定义
    switch.dc1_2_s2:
      friendly_name: 自定义
    switch.dc1_2_s3:
      friendly_name: 自定义

    switch.dc1_3:
      friendly_name: 电源开关
    switch.dc1_3_s1:
      friendly_name: 自定义
    switch.dc1_3_s2:
      friendly_name: 自定义
    switch.dc1_3_s3:
      friendly_name: 自定义