switch:
  - platform: phicomm_dc1
    name: dc1_balcony
    hidden: true
    ip: 192.168.0.111
    ports: {'1':'dc1_balcony_s1','2':'dc1_balcony_s2','3':'dc1_balcony_s3'}
#   - platform: phicomm_dc1
#     name: dc1_huayuan
#     hidden: true
#     ip: 192.168.0.112
#     ports: {'1':'dc1_huayuan_s1','2':'dc1_huayuan_s2','3':'dc1_huayuan_s3'}


sensor:
  - platform: template
    sensors:
      dc1_balcony_v:
        friendly_name: 当前电压
        value_template: "{{ states.switch.dc1_balcony.attributes.v }}"
        unit_of_measurement: V
      dc1_shufang_p:
        friendly_name: 当前功率
        value_template: "{{ states.switch.dc1_balcony.attributes.p }}"
        unit_of_measurement: W

#   - platform: template
#     sensors:
#       dc1_huayuan_v:
#         friendly_name: 当前电压
#         value_template: "{{ states.switch.dc1_huayuan.attributes.v }}"
#         unit_of_measurement: V
#       dc1_huayuan_p:
#         friendly_name: 当前功率
#         value_template: "{{ states.switch.dc1_huayuan.attributes.p }}"
#         unit_of_measurement: W

group:
  dc1_balcony:
    name: 阳台DC1排插
    view: false
    entities:
      - sensor.dc1_balcony_v
      - sensor.dc1_balcony_p
      - sensor.dc1_balcony_totale
      - switch.dc1_balcony
      - switch.dc1_balcony_s1
      - switch.dc1_balcony_s2
      - switch.dc1_balcony_s3
#   dc1_huayuan:
#     name: 花园DC1排插
#     view: false
#     entities:
#       - sensor.dc1_huayuan_v
#       - sensor.dc1_huayuan_p
#       - sensor.dc1_huayuan_totale
#       - switch.dc1_huayuan
#       - switch.dc1_huayuan_s1
#       - switch.dc1_huayuan_s2
#       - switch.dc1_huayuan_s3


homeassistant:        
  customize:
    switch.dc1_balcony:
      friendly_name: 阳台
    switch.dc1_balcony_s1:
      friendly_name: 电饭煲
    switch.dc1_balcony_s2:
      friendly_name: 热水壶
    switch.dc1_balcony_s3:
      friendly_name: 插口三
#     switch.dc1_huayuan:
#       friendly_name: 由你定
#     switch.dc1_huayuan_s1:
#       friendly_name: 由你定
#     switch.dc1_huayuan_s2:
#       friendly_name: 由你定
#     switch.dc1_huayuan_s3:
#       friendly_name: 由你定
